# Generated by Django 3.2.3 on 2021-05-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210527_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patientform',
            new_name='Patient',
        ),
    ]
