# Generated by Django 3.2.3 on 2021-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210714_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='AdminUpload',
            field=models.FileField(default='no file', upload_to='media/upload'),
        ),
    ]
