# Generated by Django 3.2.3 on 2021-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_adminupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AdminUpload',
            field=models.FileField(default='no file', upload_to='media'),
        ),
    ]
