# Generated by Django 3.2.3 on 2021-07-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_adminupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
    ]
