# Generated by Django 3.2.3 on 2021-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210721_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date2',
            field=models.DateField(auto_now=True),
        ),
    ]
