# Generated by Django 3.2.3 on 2021-07-21 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='d1',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
