# Generated by Django 3.2.3 on 2021-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_d1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='T',
            field=models.IntegerField(default=10),
        ),
    ]
