# Generated by Django 3.2.3 on 2021-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_book_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='dd/mm/yy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date2',
            field=models.DateField(verbose_name='dd/mm/yy'),
        ),
    ]
