# Generated by Django 3.2.3 on 2021-07-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210722_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date:dd/mm/yy'),
        ),
    ]
