# Generated by Django 3.2.3 on 2021-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='d1',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='dd/mm/yy'),
        ),
    ]
