# Generated by Django 3.2.3 on 2021-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date2',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
