# Generated by Django 3.2.3 on 2021-07-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210722_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='T',
        ),
    ]
