# Generated by Django 3.2.3 on 2021-07-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_book_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='dd/mm/yy'),
        ),
    ]
