# Generated by Django 3.2.3 on 2021-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_book_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date2',
            field=models.DateField(),
        ),
    ]
