# Generated by Django 3.2.3 on 2021-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
